baseURL = "https://mwittep.github.io/"
languageCode = "en-US"
title = "Mathias Witte Paz"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "/img/Mathias.jpeg"
  author = "Mathias Witte Paz"
  description = "About Mathias Witte Paz"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "mwittep"
  Email         = "mwittep@gmail.com"
  Twitter       = "wittepaz"
  LinkedIn      = "mathias-witte-paz"


## Main Menu
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
